My Internet Shop/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using MyInternetShop.Models;

namespace MyInternetShop.Models
{
    public class Order
    {
        public Order()
        {
            OrderEntities = new List<OrderEntity>();
        }

        [Key]
        public int Id { get; set; }
        [ForeignKey("User")]
        public string UserId { get; set; }
        public string Status { get; set; }
        public DateTime? Date { get; set; }
        public decimal? Cost { get; set; }

        public virtual User User { get; set; }

        public ICollection<OrderEntity> OrderEntities { get; set; }
    }
}

My Internet Shop/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyInternetShop.Models;
using MyInternetShop.ViewModels;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace MyInternetShop.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        public ApplicationContext db;
        public AdminController(ApplicationContext context)
        {
            db = context;
        }

        public async Task<IActionResult> IndexAsync()
        {
            ViewBag.Categories = await db.Categories.ToListAsync();
            return View(db.Products.ToList());
        }

        public async Task<IActionResult> CategoryAsync()
        {
            return View(await db.Categories.ToListAsync());
        }

        [HttpGet]
        public IActionResult AddCategory() => View();

        [HttpPost]
        public async Task<IActionResult> AddCategory(AddCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
               Category category = new Category { CategoryName = model.CategoryName };
               var result = db.Categories.Add(category);
               await db.SaveChangesAsync();

               return RedirectToAction("Category");
            }
            return View(model);
        }

        public async Task<IActionResult> EditCategory(int? id)
        {
            if (id != null)
            {
                Category category = await db.Categories.FirstOrDefaultAsync(p => p.Id == id);
                if (category != null)
                    return View(category);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditCategory(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Update(category);
                await db.SaveChangesAsync();
                return RedirectToAction("Category");
            }
            return View(category);
        }

        public IActionResult AddProduct()
        {
            List<Category> categories = db.Categories.ToList();
            ViewBag.Categories = categories;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(AddProductViewModel model)
        {
            Image img = null;

            if (ModelState.IsValid)
            {
                if(Request.Form.Files.Count > 0)
                {
                    var file = Request.Form.Files[0];

                    img = new Image();
                    img.ImageTitle = file.FileName;

                    MemoryStream ms = new MemoryStream();
                    file.CopyTo(ms);
                    img.ImageData = ms.ToArray();

                    ms.Close();
                    ms.Dispose();

                    await db.Images.AddAsync(img);
                    db.SaveChanges();
                }

                Product product;

                if (img != null)
                {
                    product = new Product { ProductName = model.ProductName, ImageId = img.Id, CategoryId = model.CategoryId, Price = model.Price, Quantity = model.Quantity, Description = model.Description };
                }

                else
                {
                    product = new Product { ProductName = model.ProductName, CategoryId = model.CategoryId, Price = model.Price, Quantity = model.Quantity, Description = model.Description };
                }
                
                db.Products.Add(product);
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            if (ModelState["Price"].Errors.Any())
                ModelState["Price"].Errors[0] = new ModelError("Некорректный ввод");

            if (ModelState["Quantity"].Errors.Any() && ModelState["Quantity"].Errors[0].ErrorMessage.StartsWith("The"))
                ModelState["Quantity"].Errors[0] = new ModelError("Некорректный ввод");

            ViewBag.Categories = await db.Categories.ToListAsync();

            return View(model);
        }

        [HttpPost]
        public IActionResult EditProduct(Product product, int? ImageId, bool ToDelete)
        {
            if (ModelState.IsValid)
            {
                Image img = null;

                if (Request.Form.Files.Count > 0)
                {
                    var file = Request.Form.Files[0];

                    img = new Image();
                    img.ImageTitle = file.FileName;

                    MemoryStream ms = new MemoryStream();
                    file.CopyTo(ms);
                    img.ImageData = ms.ToArray();

                    ms.Close();
                    ms.Dispose();

                    db.Images.Add(img);
                    db.SaveChanges();

                    product.ImageId = img.Id;
                    db.Products.Update(product);
                    db.SaveChanges();

                    //Deleting old image                  
                    if (ImageId != null)
                    {
                        Image OldImage = db.Images.FirstOrDefault(i => i.Id == ImageId);
                        db.Images.Remove(OldImage);
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }

                else
                {
                    if (ImageId != null & ToDelete)
                    {
                        product.ImageId = null;
                        db.Products.Update(product);
                        db.SaveChanges();

                        Image OldImage = db.Images.FirstOrDefault(i => i.Id == ImageId);
                        db.Images.Remove(OldImage);
                        db.SaveChanges();
                    }

                    else
                    {
                        db.Products.Update(product);
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
            }

            ViewBag.Categories = db.Categories.ToList();

            return View(product);
        }

        public async Task<IActionResult> EditProduct(int? id, string returnurl)
        {
            if (id != null)
            {
                Product product = await db.Products.FirstOrDefaultAsync(p => p.Id == id);
                if (product != null)
                {
                    Image image = db.Images.FirstOrDefault(i => i.Id == product.ImageId);

                    if (image != null)
                        ViewBag.ImageTitle = image.ImageTitle; 

                    ViewBag.Categories = db.Categories.ToList();
                    ViewBag.back = returnurl;
                    return View(product);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteProduct(int? id)
        {
            if (id != null)
            {
                Product product = await db.Products.FirstOrDefaultAsync(p => p.Id == id);
                
                if (product != null)
                {
                    Image image = db.Images.FirstOrDefault(i => i.Id == product.ImageId);
                    db.Products.Remove(product);

                    if(image != null)
                    db.Images.Remove(image);

                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult DeleteCategory(int? id)
        {
            try
            {
                if (id != null)
                {
                    Category category = db.Categories.FirstOrDefault(p => p.Id == id);

                    if (category != null)
                    {
                        if(category.CategoryName == "No Category")
                        {
                            ViewBag.Error = "Вы не можете удалить эту категорию";
                            return View("Category", db.Categories.ToList());
                        }

                        db.Categories.Remove(category);
                        db.SaveChanges();
                        return RedirectToAction("Category");
                    }
                }
                return NotFound();
            }

            catch (DbUpdateException)
            {
                ViewBag.Error = "Невозможно удалить категорию, в данной категории есть товары";
                return View("Category", db.Categories.ToList());
            }
        }

        public async Task<IActionResult> DetailsAsync(int? id)
        {
            if (id != null)
            {
                Product product = await db.Products.FirstOrDefaultAsync(p => p.Id == id);

                Image img = db.Images.FirstOrDefault(img => img.Id == product.ImageId);

                if(img != null)
                {
                  string imageBase64Data = Convert.ToBase64String(img.ImageData);
                  string imageDataURL = string.Format("data:image/jpg;base64,{0}", imageBase64Data);
                  ViewBag.ImageDataUrl = imageDataURL;
                }

                ViewBag.Categories = db.Categories.ToListAsync();

                return View(product);
            }
            return NotFound();
        }

        public IActionResult Orders()
        {
            var orders = db.Orders.Include(o => o.OrderEntities).ThenInclude(e => e.Product).Include(e => e.User).OrderByDescending(i => i.Date).ToList();

            ViewBag.tab = "Все заказы";

            return View(orders);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmOrderAsync(int OrderId)
        {

My Internet Shop/Controllers/UsersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyInternetShop.Models;
using MyInternetShop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace MyInternetShop.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private ApplicationContext db;
        UserManager<User> _userManager;
        SignInManager<User> _signInManager;

        public UsersController(UserManager<User> userManager, ApplicationContext context, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            db = context;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string name)
        {
            User user = await _userManager.FindByNameAsync(name);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, UserName = user.UserName, Email = user.Email, Year = user.Year };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.UserName;
                    user.Year = model.Year;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        ViewBag.Categories = await db.Categories.ToListAsync();
                        await _signInManager.SignInAsync(user, false);
                        ViewBag.UserName = user.UserName;
                        return (RedirectToAction("Index", "Home"));
                        //return View("~/Views/Home/Index.cshtml");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                var orders = db.Orders.Include(o => o.OrderEntities).Where(o => o.UserId == id);
                
                foreach(Order o in orders)
                {
                    var orderEntities = o.OrderEntities.Where(oe => oe.OrderId == o.Id);
                    db.RemoveRange(orderEntities);
                    db.Remove(o);
                }
              
                db.SaveChanges();
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, UserName = user.UserName };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    IdentityResult result =
                        await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            if (error.Description.StartsWith("Incorrect"))
                                error.Description = "Неверный пароль";

                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Orders()
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            if (user == null)
            {
                return NotFound();
            }

            var orders = db.Orders.Where(o => o.UserId == user.Id).Include(o => o.OrderEntities).ThenInclude(e => e.Product).OrderByDescending(i => i.Date).ToList();

            return View(orders);
        }

        [HttpPost]
        public async Task<IActionResult> CancelOrderAsync(int OrderId)
        {
            Order order = db.Orders.FirstOrDefault(o => o.Id == OrderId);

            if (order == null)
                return BadRequest();

            //db.Entry(order).Collection("OrderEntities").Load();

            //foreach (OrderEntity o in order.OrderEntities)
            //{
            //    db.Entry(o).Reference("Product").Load();
            //    o.Product.Quantity += o.Count;
            //}

            order.Status = Status.CancelledByUser;
            await db.SaveChangesAsync();

            return new JsonResult(new { id = order.Id, status = Status.CancelledByUser });
        }

        [HttpPost]
        public async Task<IActionResult> ResumeOrderAsync(int OrderId)
        {
            Order order = db.Orders.FirstOrDefault(o => o.Id == OrderId);

            if (order == null)
                return BadRequest();

            db.Entry(order).Collection("OrderEntities").Load();

            foreach (OrderEntity o in order.OrderEntities)
            {
                db.Entry(o).Reference("Product").Load();

                if(o.Product.Quantity < o.Count)
                {
                    return new JsonResult(new { message = "К сожалению некоторых товаров в этом заказе уже не достаточно" +
                        "\nНевозможно восстановить заказ", ProductName = o.Product.ProductName });
                }
                //o.Product.Quantity -= o.Count;
            }

            order.Status = Status.New;
            await db.SaveChangesAsync();

            return new JsonResult(new { id = order.Id, status = Status.Waiting });
        }
    }
}

My Internet Shop/Views/Users/ChangePassword.cshtml
@model MyInternetShop.ViewModels.ChangePasswordViewModel
@{
    ViewBag.Title = "Изменение пароля";
}
@*<div class="d-flex user-edit-links-cont h-40 align-items-center justify-content-between">*@
<a class="adm-link back-link-change-password" asp-controller="Users" asp-action="Edit" asp-route-name="@Model.UserName">< Назад</a>
<h2 class="text-center">Изменение пароля</h2>
@*</div>*@
<form asp-action="ChangePassword" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>

    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="UserName" />
    <div class="form-group">
        <label asp-for="OldPassword" class="control-label">Старый пароль</label>
        <input type="password" asp-for="OldPassword" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="NewPassword" class="control-label">Новый пароль</label>
        <input type="password" asp-for="NewPassword" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-outline-dark" />
    </div>
</form>
@await Html.PartialAsync("_ValidationScriptsPartial")

My Internet Shop/Views/Users/Edit.cshtml
@model MyInternetShop.ViewModels.EditUserViewModel
@{
    ViewBag.Title = "Редактирование пользователя";
}
<div class="d-flex user-edit-links-cont h-40 align-items-center justify-content-between">
    <a class="adm-link" asp-controller="Home" asp-action="Index">< Назад</a>
    <a class="adm-link user-orders-link" asp-controller="Users" asp-action="Orders">Мои заказы</a>
    <a class="adm-link" asp-action="ChangePassword" asp-route-id="@Model.Id">Сменить пароль</a>
</div>
<h2>Изменение данных</h2>
<form asp-action="Edit" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input type="text" asp-for="Email" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="UserName" class="control-label"></label>
        <input type="text" asp-for="UserName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Year" class="control-label">Год рождения</label>
        <input type="number" asp-for="Year" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
    </div>
</form>
@await Html.PartialAsync("_ValidationScriptsPartial")

My Internet Shop/Views/Users/Index.cshtml
@model IEnumerable<MyInternetShop.Models.User>
@{
    ViewBag.Title = "Список пользователей";
}

<h1 class="bg-primary text-center admin-page-header">Список пользователей</h1>
<div class="d-flex h-40 align-items-center justify-content-start">
    <a class="adm-link ml-4" asp-controller="Admin" asp-action="Index">< Назад</a>
</div>
<table class="table table-bordered table-responsive-sm">
    <thead class="text-center text-grey">
        <tr><th>Email</th><th>Имя пользователя</th><th>Год</th><th>Действия</th></tr>
    </thead>
    @foreach (var user in Model)
    {
        <tr class="font-weight-bold">
            <td>@user.Email</td>
            <td>@user.UserName</td>
            <td class="text-center">@user.Year</td>
            <td class="text-center">
                    <a class="btn btn-sm btn-primary" asp-controller="Roles" asp-action="Edit" asp-route-userid="@user.Id">Права доступа</a>
                    @*<a class="btn btn-sm btn-primary" asp-action="ChangePassword" asp-route-id="@user.Id">Сменить пароль</a>*@
            <form action="Users/Delete" method="post" class="delete-link">
                <input type="hidden" name="id" value="@user.Id" />
                <input type="submit" value="Удалить" class="btn btn-sm btn-danger" />
            </form>
            </td>
        </tr>
    }
</table>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Удаление пользователя</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Вы уверенны, что хотите удалить данного пользователя?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Отменить</button>
                <button type="button" class="btn btn-danger" onclick="sbm()">Удалить</button>
            </div>
        </div>
    </div>
</div>
<script src="~/js/ConfirmDelete.js"></script>

My Internet Shop/Views/Users/Orders.cshtml
@model IEnumerable<MyInternetShop.Models.Order>

@{
    ViewData["Title"] = "Заказы";
}
    <h1 class="text-center">Мои заказы</h1>
        <a class="adm-link orders-back-link" asp-action="Edit" asp-route-name="@User.Identity.Name">< Назад</a>
    @foreach (Order order in Model)
    {
        <h2 class="text-center mt-5">Заказ № @order.Id</h2>
        <table class="table table-responsive-sm text-center category-table">
            <thead class="text-grey">
                <tr>
                    <th>Дата</th>
                    <th>Стоимость</th>
                    <th>Статус</th>
                </tr>
            </thead>
            <tbody>
                <tr class="font-weight-bold">
                    <td>@Html.DisplayFor(modelItem => order.Date)</td>
                    <td>@Html.DisplayFor(modelItem => order.Cost)</td>
                    @{if (order.Status == Status.Waiting)
                        {
                            <td class="text-warning" id="@order.Id.ToString()">@Html.DisplayFor(modelItem => order.Status)</td>
                        }
                        else if (order.Status == Status.Confirmed)
                        {
                            <td id="@order.Id.ToString()" class="text-success">@Html.DisplayFor(modelItem => order.Status)</td>
                        }
                        else if (order.Status == Status.Cancelled)
                        {
                            <td id="@order.Id.ToString()" class="text-danger">@Html.DisplayFor(modelItem => order.Status)</td>
                        }
                        else if (order.Status == Status.CancelledByUser)
                        {
                            <td id="@order.Id.ToString()" class="text-danger">@Html.DisplayFor(modelItem => order.Status)</td>
                        }
                        else if (order.Status == Status.New)
                        {
                            <td id="@order.Id.ToString()" class="text-warning">@Status.Waiting</td>
                        }
                        else
                        {
                            {
                                <td class="text-darkblue" id="@order.Id.ToString()">@Html.DisplayFor(modelItem => order.Status)</td>
                            }
                        }
                    }
                </tr>
            </tbody>
        </table>
        <div class="container">
            <ol class="oredered-products-list">
                @foreach (var item in order.OrderEntities)
                {
                    <li>&nbsp;@item.Product.ProductName&nbsp;&nbsp;&nbsp;Цена:&nbsp;@item.Product.Price&nbsp;&nbsp; Количество:&nbsp;@item.Count</li>
                }
            </ol>
            <div id="button" class="d-flex justify-content-center">
                @{ if (order.Status == Status.Waiting | order.Status == Status.New)
                    {
                        <form method="post" asp-action="CancelOrder" data-ajax="true" data-ajax-method="post" data-ajax-success="CancelSuccess" data-ajax-failure="Failure">
                            <input type="hidden" name="OrderId" value="@order.Id" />
                            <button type="submit" class="btn btn-lg btn-danger user-orders-button">Отменить</button>
                        </form>
                    }
                    else if (order.Status == Status.CancelledByUser)
                    {
                        <form method="post" asp-action="ResumeOrder" data-ajax="true" data-ajax-method="post" data-ajax-success="ResumeSuccess" data-ajax-failure="Failure">
                            <input type="hidden" name="OrderId" value="@order.Id" />
                            <button type="submit" class=" btn btn-lg btn-success user-orders-button">Возобновить</button>
                        </form>
                    }
                }
            </div>
        </div>
        <script src="~/lib/jquery.unobtrusive-ajax/jquery.unobtrusive-ajax.min.js"></script>
        <script src="~/js/OrdersUser.js"></script>
    }